### ISSUE TITLE
Add Rubocop

### ISSUE THREAD

**Issue by bnd5k** [buildingblocklabs/xypn_seo#2]
This app should be obeying ruby best practices.  Let's add the Rubocop gem.   @J-Rapp  can you take care of adding and configuring Rubocop?

**Comment by jakedjohnson** [comment]
Rubocop added to development and code is meeting style guide specs

https://github.com/buildingblocklabs/xypn_seo/blob/master/Gemfile

**Comment by bnd5k** [comment]
Terrific.  Thanks!
